### ISSUE TITLE
Web Playground

### ISSUE THREAD

**Issue by janpio** [williamluke4/prisma-viewer#7]
It would be awesome if we could use this to create a small Web Playground, where you can just paste your Prisma schema and click a button to go to the generated diagram.

**Comment by janpio** [comment]
Features for first version:
- Textarea to paste schema content
- Button to switch to diagram view

Additional possible features:
- Textarea has syntax highlighting and validation for Prisma Schema
- Drag file onto textarea to upload and load schema content into textarea

**Comment by williamluke4** [comment]
You can try this out using `npm i -g prisma-viewer@canary` 
The code is on the `ace-editor` branch

**Comment by schickling** [comment]
Is there an online version (e.g. on Now or Netlify) that I can try out?

**Comment by janpio** [comment]
How do I run that properly @williamluke4? 
Start in an existing project, then iterate on the model?
(That is how I got something to work for now)

**Comment by williamluke4** [comment]
@janpio Currently it does not save the model when you change it in the browser. Still early days but getting there.

@schickling Just been doing some tests using `@prisma/sdk` on a Nextjs API route which seems to work pretty well. I'll update you once there is a site for it.

## Questions

- **Q1**:  If hosted on a site then it would not be able to access and edit your `*.prisma` file. You would have to upload it then edit/view then download the file. Not great DX. This is why I went down the CLI route. Does anyone have any better ideas?

- **Q2**: If I spend more time on this is **Prisma** willing to support the project?

- **Q3**: What scope do you guys see for this?

**Comment by williamluke4** [comment]
@schickling https://prisma-flow.now.sh/ 
Moving the models around is a bit wonky currently

**Comment by williamluke4** [comment]
Closing as I don't have time
